### ISSUE TITLE
Trouble installing from GitHub 

### ISSUE THREAD

**Issue by kyleeannsmith** [jashu/beset#4]
I am getting an error message when trying to install this package on GitHub. Please let me know if you see a way to work through this. 

Thank you 

Error: Failed to install 'beset' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> Quitting from lines 57-58 (validate.Rmd) 
E> Error: processing vignette 'validate.Rmd' failed with diagnostics:
E> The engine "block2" is for R Markdown only
E> --- failed re-building ‘validate.Rmd’
E> 
E> SUMMARY: processing the following files failed:
E>   ‘best-subsets.Rmd’ ‘elastic-net.Rmd’ ‘validate.Rmd’
E> 
E> Error: Vignette re-building failed.
E> Execution halted

**Comment by jashu** [comment]
This is an issue with building the vignettes, so the expedient solution will be to set `build_vignettes` to `FALSE` (or just drop the `build_vignettes` argument altogether) when you try to install. The package should still install; you just won't have access to the tutorials. As for why they're not building or how to get them to build, you will need to consult the `devtools` documentation. It sounds like maybe you don't have "rmarkdown" installed?
